export interface HealthCheckEventPayload {
  serviceId: string;
  checkTimestamp: string;
  statusCode: number | null;
  latencyMs: number;
  isSuccess: boolean;
  failureReason: string | null;
  environment: string;
}

export interface CloudPulseEvent<T = unknown> {
  id: string; // Stable UUID generated by producer
  type: string; // e.g. "cloudpulse.health-check.v1"
  version: string; // e.g. "1.0.0"
  producer: string; // e.g. "cloudpulse-monitoring-worker"
  timestamp: string; // ISO 8601
  payload: T;
}

export type HealthCheckEvent = CloudPulseEvent<HealthCheckEventPayload>;

export interface DeadLetterEvent {
  originalEventId: string;
  originalTopic: string;
  errorReason: string;
  failedAt: string;
  retryAttempts: number;
  rawPayload: string;
}
